[tool.isort]
line_length = 79
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true

[tool.black]
line-length = 79
skip-string-normalization = true
experimental-string-processing = true

[tool.pyright]
typeCheckingMode = "strict"
reportUnsupportedDunderAll = false
