require('plugins.plugins')
require('plugins.nvim-lspconfig')
require('plugins.nvim-compe')
require('plugins.nvim-treesitter')
require('plugins.trouble')
require('plugins.kommentary')
require('plugins.themes')
require('plugins.nvim-tree')
